#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : passwdqc
Version  : 2.0.3
Release  : 3
URL      : https://github.com/openwall/passwdqc/archive/refs/tags/v2.0.3.tar.gz
Source0  : https://github.com/openwall/passwdqc/archive/refs/tags/v2.0.3.tar.gz
Summary  : A password/passphrase strength checking and policy enforcement toolset.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: passwdqc-bin = %{version}-%{release}
Requires: passwdqc-lib = %{version}-%{release}
Requires: passwdqc-license = %{version}-%{release}
Requires: passwdqc-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Set-lib-paths.patch

%description
passwdqc is a password/passphrase strength checking and policy
enforcement toolset, including a PAM module (pam_passwdqc), command-line
programs (pwqcheck, pwqfilter, and pwqgen), and a library (libpasswdqc).

pam_passwdqc is normally invoked on password changes by programs such as
passwd(1).  It is capable of checking password or passphrase strength,
enforcing a policy, and offering randomly-generated passphrases, with
all of these features being optional and easily (re-)configurable.

pwqcheck and pwqgen are standalone password/passphrase strength checking
and random passphrase generator programs, respectively, which are usable
from scripts.

The pwqfilter program searches, creates, or updates binary passphrase
filter files, which can also be used with pwqcheck and pam_passwdqc.

libpasswdqc is the underlying library, which may also be used from
third-party programs.

%package bin
Summary: bin components for the passwdqc package.
Group: Binaries
Requires: passwdqc-license = %{version}-%{release}

%description bin
bin components for the passwdqc package.


%package dev
Summary: dev components for the passwdqc package.
Group: Development
Requires: passwdqc-lib = %{version}-%{release}
Requires: passwdqc-bin = %{version}-%{release}
Provides: passwdqc-devel = %{version}-%{release}
Requires: passwdqc = %{version}-%{release}

%description dev
dev components for the passwdqc package.


%package lib
Summary: lib components for the passwdqc package.
Group: Libraries
Requires: passwdqc-license = %{version}-%{release}

%description lib
lib components for the passwdqc package.


%package license
Summary: license components for the passwdqc package.
Group: Default

%description license
license components for the passwdqc package.


%package man
Summary: man components for the passwdqc package.
Group: Default

%description man
man components for the passwdqc package.


%prep
%setup -q -n passwdqc-2.0.3
cd %{_builddir}/passwdqc-2.0.3
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689176819
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1689176819
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/passwdqc
cp %{_builddir}/passwdqc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/passwdqc/5ad990531eb15442c0b9095476aba24445066f86 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pwqcheck
/usr/bin/pwqfilter
/usr/bin/pwqgen

%files dev
%defattr(-,root,root,-)
/usr/include/passwdqc.h
/usr/lib64/libpasswdqc.so
/usr/lib64/pkgconfig/passwdqc.pc
/usr/share/man/man3/libpasswdqc.3
/usr/share/man/man3/passwdqc_check.3
/usr/share/man/man3/passwdqc_params_free.3
/usr/share/man/man3/passwdqc_params_load.3
/usr/share/man/man3/passwdqc_params_parse.3
/usr/share/man/man3/passwdqc_params_reset.3
/usr/share/man/man3/passwdqc_random.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpasswdqc.so.1
/usr/lib64/security/pam_passwdqc.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/passwdqc/5ad990531eb15442c0b9095476aba24445066f86

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pwqcheck.1
/usr/share/man/man1/pwqfilter.1
/usr/share/man/man1/pwqgen.1
/usr/share/man/man5/passwdqc.conf.5
/usr/share/man/man8/pam_passwdqc.8
